steps:
  # 1. Dockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/fastapi-cloudrun/fastapi-service:$COMMIT_SHA'
      - '.'

  # 2. ビルドしたイメージをArtifact Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/fastapi-cloudrun/fastapi-service:$COMMIT_SHA'

  # 3. Cloud Runに新しいイメージをデプロイ
  - name: 'gcr.io/google-cloud-sdk/gcloud'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fastapi-service'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/fastapi-cloudrun/fastapi-service:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--no-allow-unauthenticated'
      - '--port'
      - '8080'

# デプロイに使用したイメージを登録
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/fastapi-cloudrun/fastapi-service:$COMMIT_SHA'
